FROM centos:6
ENV HOME /
RUN yum update -y
RUN yum install -y rpm-build redhat-rpm-config rpmdevtools cmake gcc-c++ tar
RUN rpmdev-setuptree
RUN echo '%dist   .el6' >> /.rpmmacros
ADD ./rpmbuild/ /rpmbuild/
RUN chown root:root -R /rpmbuild
RUN rpmbuild -ba /rpmbuild/SPECS/h2o.spec
RUN tar -czf /tmp/h2o.tar.gz -C /rpmbuild RPMS SRPMS
CMD ["/bin/true"]
